#!/usr/bin/env bash
#installs nginx, listens on port 80, and returns a page with a string
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start