#!/usr/bin/env bash
#installs nginx, listens on port 80, and returns a page with a string
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > index.html
sudo service nginx start