#!/usr/bin/env bash
#Install nginx on your web-01 server

apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP' # port 80 only
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start