#!/usr/bin/env bash
# Install nginx web server
#!/usr/bin/env bash
#Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
new_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}"
sudo sed -i '0,/server_name _;/{s|server_name _;|$new_string|}' /etc/nginx/sites-available/default
sudo service nginx start
