#!/usr/bin/env bash
#Install nginx on your web-01 server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
string = "server_name _;\n\n\tlocation /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4}"
sudo sed -i '0, /server_name _; /{s|server_name _;|$string|}' /etc/nginx/sites-available/default
service nginx restart