#!/usr/bin/env bash
#installs Nginx, sets it so that /redirect_me redirects to another page, there is a custom 404 page, and HTTP response contains a custom header
apt-get update
apt-get -y install haproxy
printf "\n frontend holberton
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
    mode http
    balance roundrobin
    server 4639-web-01  54.82.203.224
    server 4639-web-02  3.208.24.77" >> /etc/haproxy/haproxy.cfg
service haproxy restart